name: Deploy Development

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to server and deploy
        
        with:
          
          script: cd ${{ secrets.DEV_PATH }} && ls && git pull && docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build -d
